services:
  backend: 
    build: . # location of the Dockerfile for the backend
    ports:
      - '8080:8080'
    volumes:
      - sqlite_data:/app/db # internally, the app looks at ./db/database.db 
    restart: unless-stopped

volumes:
  sqlite_data: